/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM_L.h"
#include "PWM_R.h"
#include "Direction_L.h"
#include "Direction_R.h"
#include "Motor_L_1_aliases.h"
#include "Motor_L_1.h"
#include "Motor_L_2_aliases.h"
#include "Motor_L_2.h"
#include "Motor_R_1_aliases.h"
#include "Motor_R_1.h"
#include "Motor_R_2_aliases.h"
#include "Motor_R_2.h"
#include "Clock_1.h"
#include "QuadDec_L.h"
#include "QuadDec_R.h"
#include "Phase_L_A_aliases.h"
#include "Phase_L_A.h"
#include "Phase_L_B_aliases.h"
#include "Phase_L_B.h"
#include "Phase_R_A_aliases.h"
#include "Phase_R_A.h"
#include "Phase_R_B_aliases.h"
#include "Phase_R_B.h"
#include "TIA.h"
#include "Red_Pin_aliases.h"
#include "Red_Pin.h"
#include "Green_Pin_aliases.h"
#include "Green_Pin.h"
#include "Blue_Pin_aliases.h"
#include "Blue_Pin.h"
#include "PD_aliases.h"
#include "PD.h"
#include "IDAC8.h"
#include "ADC.h"
#include "UTimer.h"
#include "Trigger.h"
#include "USelect.h"
#include "Echo0_aliases.h"
#include "Echo0.h"
#include "Echo1_aliases.h"
#include "Echo1.h"
#include "Echo2_aliases.h"
#include "Echo2.h"
#include "Echo3_aliases.h"
#include "Echo3.h"
#include "Trigger3_aliases.h"
#include "Trigger3.h"
#include "Trigger2_aliases.h"
#include "Trigger2.h"
#include "Trigger1_aliases.h"
#include "Trigger1.h"
#include "Trigger0_aliases.h"
#include "Trigger0.h"
#include "UClock.h"
#include "Echo.h"
#include "UART.h"
#include "Flag_aliases.h"
#include "Flag.h"
#include "QuadDec_L_Cnt16.h"
#include "QuadDec_R_Cnt16.h"
#include "ADC_Ext_CP_Clk.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

